# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 19d31d3f87d1b2b2c1fc4087f94afa28da7f7143a4ec7734a06e540ff696f9ce985faff0269ee450f6669cab0596c4977187508293ed42fc0c2cfdace9efe739

test:
  secret_key_base: ce897cac664e29f3b67d61ac8ff3c640b8334690f769fba6bc13c6fd68b7c53291771bb34c252eb9fa9dd511cb605d82d4e8a73a99531704968ff420ea064c7f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
